### ISSUE TITLE
Compose a Proper Abstract

### ISSUE THREAD

**Issue by Novators** [Novators/sqrl-spec#2]
Abstract needs to be reviewed and probably re-written.

**Comment by shanedk** [comment]
Is there something specific you feel is missing or wrong with it?

**Comment by Novators** [comment]
What I originally wrote is essentially a few "selling points" for laymen.  I think it needs a bit more technical detail about how it does these things, the major technologies involved, etc.  I was struggling to word these additions clearly and concisely, though.

**Comment by Novators** [comment]
That looks a lot better.  Thanks, Shane.
