### ISSUE TITLE
Fix formatting

### ISSUE THREAD

**Issue by shanedk** [Novators/sqrl-spec#29]
I think the reason we're having so many conflicts with new and changed section has to do with the formatting. So much of the XML, especially the sections marked TODO, are all on one line of text. GitHub seems to work better when files are divided by lines, so you don't end up replacing one entire line of text with another. So I think it would be better if the XML were reformatted with tags on indented lines.

I'd be happy to take some time to work on this.

**Comment by Novators** [comment]
Good point.  This is caused by the way my XML editor saves files.  I can add a step to my toolchain to fix this, I believe, so no need to spend time manually changing it.
