### ISSUE TITLE
Section for Logo and font?

### ISSUE THREAD

**Issue by shanedk** [Novators/sqrl-spec#32]
Since SQRL has a standard logo and font, should we have a section for that? Or is that something that doesn't belong in an RFC?

**Comment by Novators** [comment]
For now, I think that it would be fine to add to the "Best Practices" section.  Before RFC submission, however, I suspect that this and a lot of our other content will need to be split off into a separate implementation guide.  I guess we'll figure that out when we get to the editing phase.

**Comment by shanedk** [comment]
Since it applies to both clients and servers, I made them separate sections under Best Practices.

**Comment by Novators** [comment]
Sounds good.  Thanks!
